# Context Optimization Workflow
name: context-optimize
description: "Analyze and optimize project context for efficient token usage. Modes: analyze (report only), archive (move completed artifacts), full (all optimizations)"
author: "BMad"

# Model recommendation - lightweight task
recommended_model: haiku
model_rationale: "Context optimization is procedural analysis and file operations - doesn't require advanced reasoning."

# Critical variables from config
config_source: "{project-root}/_bmad/bmm/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated
planning_artifacts: "{config_source}:planning_artifacts"
implementation_artifacts: "{config_source}:implementation_artifacts"
output_folder: "{config_source}:output_folder"

# Workflow components
installed_path: "{project-root}/_bmad/bmm/workflows/4-implementation/context-optimize"
instructions: "{installed_path}/instructions.md"
template: false

# Files to analyze
variables:
  sprint_status: "{implementation_artifacts}/sprint-status.yaml"
  archive_folder: "{output_folder}/archive"
  claude_md: "{project-root}/CLAUDE.md"
  project_context: "{output_folder}/project-context.md"
  optimization_guide: "{output_folder}/context-optimization-guide.md"

# Default mode if not specified
default_mode: analyze

# Available modes
modes:
  analyze:
    description: "Report context issues without making changes"
    actions: [scan_files, calculate_sizes, detect_redundancy, report]
  archive:
    description: "Archive completed epic artifacts"
    actions: [scan_files, detect_completed, archive_artifacts, report]
  full:
    description: "Full optimization: archive + shard + cleanup"
    actions: [scan_files, detect_completed, archive_artifacts, detect_large_files, suggest_sharding, cleanup_redundant, update_claude_md, report]

standalone: true
